//! Agent awareness protocol.
//!
//! Generates AGENTS.md, per-agent config files, and environment context so that
//! CLI agents (Claude Code, Codex, Pi, Gemini) automatically know they are inside
//! a pyobox-managed worktree.

use pyobox_types::{AgentKind, PyoboxConfig, Result};

/// Generate AGENTS.md content for a specific worktree context.
pub fn generate_agents_md(config: &PyoboxConfig, worktree_id: &str) -> Result<String> {
    Ok(format!(
        r#"# Agent Instructions (auto-generated by pyobox)

You are inside a pyobox-managed worktree.

- **Main repo**: {repo}
- **Worktree ID**: {wt}
- **Shared DB**: {db_url} (minisqlite)
- **Other agents**: Run `pyobox list-agents` to see who else is working

## Rules
1. Do NOT create your own git worktrees. Use the worktree at the path above.
2. All code changes go in this worktree. Push from the main repo.
3. The shared database is at `$PYOBOX_DB_URL`.
4. When done: run `pyobox destroy-agent` to clean up.
"#,
        repo = config.repo_path,
        wt = worktree_id,
        db_url = config.db_url,
    ))
}

/// Generate a per-agent config file for the given agent kind.
pub fn generate_agent_config(agent: &AgentKind, config: &PyoboxConfig) -> Result<String> {
    match agent {
        AgentKind::Claude => Ok(format!(
            r#"{{
  "projectInstructions": "You are in a pyobox-managed worktree. Main repo at {repo}. Shared DB at {db}. Do not create worktrees."
}}"#,
            repo = config.repo_path,
            db = config.db_url
        )),
        AgentKind::Codex => Ok(format!(
            r#"{{
  "instructions": "pyobox worktree at {repo}. DB at {db}."
}}"#,
            repo = config.repo_path,
            db = config.db_url
        )),
        AgentKind::Pi => Ok(format!(
            r#"# pi agent context for pyobox
# Main repo: {repo}
# DB: {db}
# You are in a managed worktree — do not create your own.
"#,
            repo = config.repo_path,
            db = config.db_url
        )),
        AgentKind::Gemini => Ok(format!(
            r#"pyobox environment:
  repo: {repo}
  db: {db}
  worktree: managed — do not create your own
"#,
            repo = config.repo_path,
            db = config.db_url
        )),
        AgentKind::Other(_) => Ok(format!(
            "pyobox worktree at {repo}. DB at {db}.",
            repo = config.repo_path,
            db = config.db_url
        )),
    }
}

/// Detect which agent (if any) is running in the current process tree.
#[cfg(not(target_arch = "wasm32"))]
pub fn detect_current_agent() -> Option<AgentKind> {
    let proc_self = std::fs::read_to_string("/proc/self/status").ok()?;
    for line in proc_self.lines() {
        if line.starts_with("Name:\t") {
            let name = line.trim_start_matches("Name:\t");
            return match name {
                "claude" | "claude-code" => Some(AgentKind::Claude),
                "codex" => Some(AgentKind::Codex),
                "pi" => Some(AgentKind::Pi),
                "gemini" => Some(AgentKind::Gemini),
                _ => None,
            };
        }
    }
    None
}

/// WASM stub for agent detection.
#[cfg(target_arch = "wasm32")]
pub fn detect_current_agent() -> Option<AgentKind> {
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_agents_md() {
        let config = PyoboxConfig::default();
        let md = generate_agents_md(&config, "wt-1").unwrap();
        assert!(md.contains("pyobox-managed worktree"));
    }

    #[test]
    fn test_generate_all_agent_configs() {
        let config = PyoboxConfig::default();
        for agent in &[
            AgentKind::Claude,
            AgentKind::Codex,
            AgentKind::Pi,
            AgentKind::Gemini,
        ] {
            let cfg = generate_agent_config(agent, &config).unwrap();
            assert!(!cfg.is_empty());
        }
    }
}
